- Update License tag for new Licensing Guidelines compliance - Don't regenerate all the autoxxx stuff (not needed) this fixes building     with the latest intltool

diff --git a/gnumeric-1.6.3-gda3.patch b/gnumeric-1.6.3-gda3.patch
--- a/gnumeric-1.6.3-gda3.patch
+++ b/gnumeric-1.6.3-gda3.patch
@@ -1,3 +1,93 @@
+--- gnumeric-1.6.3/configure.orig	2007-08-22 13:08:26.000000000 +0200
++++ gnumeric-1.6.3/configure	2007-08-22 13:08:26.000000000 +0200
+@@ -22088,12 +22088,12 @@ if test -n "$PKG_CONFIG"; then
+         pkg_cv_GDA_CFLAGS="$GDA_CFLAGS"
+     else
+         if test -n "$PKG_CONFIG" && \
+-    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"libgda-2.0 >= 1.3.0\"") >&5
+-  ($PKG_CONFIG --exists --print-errors "libgda-2.0 >= 1.3.0") 2>&5
++    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"libgda-3.0 >= 1.3.0\"") >&5
++  ($PKG_CONFIG --exists --print-errors "libgda-3.0 >= 1.3.0") 2>&5
+   ac_status=$?
+   echo "$as_me:$LINENO: \$? = $ac_status" >&5
+   (exit $ac_status); }; then
+-  pkg_cv_GDA_CFLAGS=`$PKG_CONFIG --cflags "libgda-2.0 >= 1.3.0" 2>/dev/null`
++  pkg_cv_GDA_CFLAGS=`$PKG_CONFIG --cflags "libgda-3.0 >= 1.3.0" 2>/dev/null`
+ else
+   pkg_failed=yes
+ fi
+@@ -22106,12 +22106,12 @@ if test -n "$PKG_CONFIG"; then
+         pkg_cv_GDA_LIBS="$GDA_LIBS"
+     else
+         if test -n "$PKG_CONFIG" && \
+-    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"libgda-2.0 >= 1.3.0\"") >&5
+-  ($PKG_CONFIG --exists --print-errors "libgda-2.0 >= 1.3.0") 2>&5
++    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"libgda-3.0 >= 1.3.0\"") >&5
++  ($PKG_CONFIG --exists --print-errors "libgda-3.0 >= 1.3.0") 2>&5
+   ac_status=$?
+   echo "$as_me:$LINENO: \$? = $ac_status" >&5
+   (exit $ac_status); }; then
+-  pkg_cv_GDA_LIBS=`$PKG_CONFIG --libs "libgda-2.0 >= 1.3.0" 2>/dev/null`
++  pkg_cv_GDA_LIBS=`$PKG_CONFIG --libs "libgda-3.0 >= 1.3.0" 2>/dev/null`
+ else
+   pkg_failed=yes
+ fi
+@@ -22130,9 +22130,9 @@ else
+         _pkg_short_errors_supported=no
+ fi
+         if test $_pkg_short_errors_supported = yes; then
+-	        GDA_PKG_ERRORS=`$PKG_CONFIG --short-errors --errors-to-stdout --print-errors "libgda-2.0 >= 1.3.0"`
++	        GDA_PKG_ERRORS=`$PKG_CONFIG --short-errors --errors-to-stdout --print-errors "libgda-3.0 >= 1.3.0"`
+         else
+-	        GDA_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "libgda-2.0 >= 1.3.0"`
++	        GDA_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "libgda-3.0 >= 1.3.0"`
+         fi
+ 	# Put the nasty error message in config.log where it belongs
+ 	echo "$GDA_PKG_ERRORS" >&5
+@@ -22158,12 +22158,12 @@ if test -n "$PKG_CONFIG"; then
+         pkg_cv_GNOMEDB_CFLAGS="$GNOMEDB_CFLAGS"
+     else
+         if test -n "$PKG_CONFIG" && \
+-    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"libgnomedb-2.0 >= 1.3.0\"") >&5
+-  ($PKG_CONFIG --exists --print-errors "libgnomedb-2.0 >= 1.3.0") 2>&5
++    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"libgnomedb-3.0 >= 1.3.0\"") >&5
++  ($PKG_CONFIG --exists --print-errors "libgnomedb-3.0 >= 1.3.0") 2>&5
+   ac_status=$?
+   echo "$as_me:$LINENO: \$? = $ac_status" >&5
+   (exit $ac_status); }; then
+-  pkg_cv_GNOMEDB_CFLAGS=`$PKG_CONFIG --cflags "libgnomedb-2.0 >= 1.3.0" 2>/dev/null`
++  pkg_cv_GNOMEDB_CFLAGS=`$PKG_CONFIG --cflags "libgnomedb-3.0 >= 1.3.0" 2>/dev/null`
+ else
+   pkg_failed=yes
+ fi
+@@ -22176,12 +22176,12 @@ if test -n "$PKG_CONFIG"; then
+         pkg_cv_GNOMEDB_LIBS="$GNOMEDB_LIBS"
+     else
+         if test -n "$PKG_CONFIG" && \
+-    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"libgnomedb-2.0 >= 1.3.0\"") >&5
+-  ($PKG_CONFIG --exists --print-errors "libgnomedb-2.0 >= 1.3.0") 2>&5
++    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"libgnomedb-3.0 >= 1.3.0\"") >&5
++  ($PKG_CONFIG --exists --print-errors "libgnomedb-3.0 >= 1.3.0") 2>&5
+   ac_status=$?
+   echo "$as_me:$LINENO: \$? = $ac_status" >&5
+   (exit $ac_status); }; then
+-  pkg_cv_GNOMEDB_LIBS=`$PKG_CONFIG --libs "libgnomedb-2.0 >= 1.3.0" 2>/dev/null`
++  pkg_cv_GNOMEDB_LIBS=`$PKG_CONFIG --libs "libgnomedb-3.0 >= 1.3.0" 2>/dev/null`
+ else
+   pkg_failed=yes
+ fi
+@@ -22200,9 +22200,9 @@ else
+         _pkg_short_errors_supported=no
+ fi
+         if test $_pkg_short_errors_supported = yes; then
+-	        GNOMEDB_PKG_ERRORS=`$PKG_CONFIG --short-errors --errors-to-stdout --print-errors "libgnomedb-2.0 >= 1.3.0"`
++	        GNOMEDB_PKG_ERRORS=`$PKG_CONFIG --short-errors --errors-to-stdout --print-errors "libgnomedb-3.0 >= 1.3.0"`
+         else
+-	        GNOMEDB_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "libgnomedb-2.0 >= 1.3.0"`
++	        GNOMEDB_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "libgnomedb-3.0 >= 1.3.0"`
+         fi
+ 	# Put the nasty error message in config.log where it belongs
+ 	echo "$GNOMEDB_PKG_ERRORS" >&5
 --- gnumeric-1.6.3/configure.in.orig	2007-05-01 18:21:36.000000000 -0400
 +++ gnumeric-1.6.3/configure.in	2007-05-01 18:22:54.000000000 -0400
 @@ -369,11 +369,11 @@
